site_name: hyc_wiki
site_url:
repo_url: https://github.com/llspark/hyc_wiki
repo_name: GitHub
edit_uri: edit/master/docs/
site_description:
site_author: heyc
copyright:
google_analytics: ['UA-36723568-3', 'mkdocs.org']
remote_branch: gh-pages
remote_name: origin
nav:
    - 'Introduction': 'index.md'
    - 'ubuntu_homeset':
         - 'mkdocs': 'ubuntu_homeset/app_mkdocs.md'
    - 'alicloud':
         - 'myweb-init': 'alicloud/myweb_init.md'
    - 'About':
         - 'License': 'about/license.md'
theme:
  name: material
docs_dir: docs
site_dir: site
extra_css:
extra_javascript:
extra_templates:
extra:
    version: 1.0
use_directory_urls: true
strict: false
dev_addr: 127.0.0.1:8000
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
plugins:
    - search:
        separator: '[\s\-\.]+'
